import Head from "next/head";
import ContentfulApi from "@ctfl/Api";
import StreamersGrid from "@components/StreamersGrid";

export default function Index({ streamers }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{streamers.total}</h1>
        <StreamersGrid streamers={streamers.items} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const streamers = await ContentfulApi.getAllStreamers();

  return {
    props: {
      streamers,
    },
  };
}
