name: "Get Streamers"
on:
  workflow_dispatch
jobs:
  build-streamers-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps
        run: npm install
      - name: Run script
        run: npm run getstreamers
      - name: Commit changes
        run: |
          something_changed=`git diff-index --exit-code --ignore-submodules HEAD`
          if [ -n "$something_changed" ]
          then
              echo "Something changed, committing"
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "get-streamers.js updated the streamers.json file"
              git push -f origin master:stream-data
              exit 0
          else
              echo "No changes, exiting"
              exit 0
          fi
        shell: bash {0}
