name: "Get Streamers"
on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
jobs:
  build-streamers-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps
        run: npm install
      - name: Run script
        env: # Or as an environment variable
          CTFL_SPACE_ID: ${{ secrets.CTFL_SPACE_ID }}
          CTFL_ACCESS_TOKEN: ${{ secrets.CTFL_ACCESS_TOKEN }}
          CTFL_JSON_ENTRY_ID: ${{ secrets.CTFTL_JSON_ENTRY_ID }}
          CTFL_JSON_SPACE_ID: ${{ secrets.CTFTL_JSON_SPACE_ID }}
          CTFL_JSON_UPDATE_TOKEN: ${{ secrets.CTFL_JSON_UPDATE_TOKEN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          VERCEL_DEPLOY_GH_ACTION_HOOK: ${{ secrets.VERCEL_DEPLOY_GH_ACTION_HOOK }}
        run: npm run getstreamers